version: "3.7"

services:
  frontend:
    image: playlist-app:latest
    build:
      context: .
      dockerfile: dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3001:3001
    environment:
      - NODE_DEV=development
    command: ["npx", "nodemon", "./index.js"]

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playlist-app-db
    ports:
      - 5433:5432
    volumes:
      - ./data/create-docker-database.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
