services:
  frontend:
    image: playlist-app:latest
    build:
      context: .
      dockerfile: dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    environment:
      - NODE_DEV=development
    #command: ["npm", "run", "build"]

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playlist-app-db
    ports:
      - 5433:5432
    volumes:
      - ./data/create-docker-database.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
