services:
  frontend:
    image: playlist-app:latest
    build:
      context: .
      dockerfile: dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    environment:
      - NODE_DEV=development
    #command: ["npm", "run", "build"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: pw4d5e3hfs83
      POSTGRES_USER: playlist-app-db
    ports:
      - 5433:5432
    volumes:
      - ./data/create-docker-database.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
